name: Terraform apply 

on:
  workflow_dispatch:  # Manually trigger workflow

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Terraform Scan Install
        run: |
          curl --location https://github.com/accurics/terrascan/releases/download/v1.9.0/terrascan_1.9.0_Linux_x86_64.tar.gz --output terrascan.tar.gz
          tar -xf terrascan.tar.gz terrascan
          rm terrascan.tar.gz
          install terrascan /usr/local/bin
          rm terrascan
          terrascan scan -t azure  # Modify this line as needed
        continue-on-error: true

      - name: Install Checkov
        run: |
          pip install checkov
      - name: Run Checkov
        run: checkov --quiet -d .
        continue-on-error: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Login to GCP
        uses: 'google-github-actions/auth@v0.4.0'
        with:
         credentials_json: '${{ secrets.GCP_SA_KEY  }}'    

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Plan
        run: terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

  terracost:
    name: "Terracost Analysis"
    runs-on: ubuntu-latest
    needs: ["terraform"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Terracost
        run: curl -Ls https://github.com/cycloidio/terracost/releases/latest/download/terracost_$(uname)_amd64 -o terracost && chmod +x terracost

      - name: Run Terracost Analysis
        run: |
        terracost estimate --output=json > terracost.json

      - name: Upload Terracost Results
        uses: actions/upload-artifact@v2
        with:
          name: terracost-results
          path: terracost.json          